"""Add category to expenses

Revision ID: 94aad27cc4eb
Revises: ada74739fae7
Create Date: 2026-06-11 12:41:06.735405

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '94aad27cc4eb'
down_revision: Union[str, Sequence[str], None] = 'ada74739fae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the PostgreSQL Enum type
    expense_category = sa.Enum(
        'FOOD',
        'TRAVEL',
        'SHOPPING',
        'BILLS',
        'ENTERTAINMENT',
        'OTHER',
        name='expensecategory'
    )
    expense_category.create(op.get_bind())

    op.add_column('expenses', sa.Column('category', expense_category, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'category')

    # Drop the PostgreSQL Enum type
    expense_category = sa.Enum(name='expensecategory')
    expense_category.drop(op.get_bind())
    # ### end Alembic commands ###
