"""create products and drop expenses

Revision ID: e1ca832de1f0
Revises: 73159613d6fe
Create Date: 2026-06-29 18:41:41.208992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1ca832de1f0'
down_revision: Union[str, Sequence[str], None] = '73159613d6fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop any pre-existing productcategory type to avoid duplicate object errors
    op.execute("DROP TYPE IF EXISTS productcategory CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('ELECTRONICS', 'CLOTHING', 'FOOD', 'BOOKS', 'BEAUTY', 'HOUSEHOLD', name='productcategory'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.drop_table('expenses')
    # ### end Alembic commands ###

    # Clean up the old expensecategory Enum type
    op.execute("DROP TYPE IF EXISTS expensecategory CASCADE")


def downgrade() -> None:
    """Downgrade schema."""
    # Drop any pre-existing expensecategory type to avoid duplicate object errors
    op.execute("DROP TYPE IF EXISTS expensecategory CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('FOOD', 'TRAVEL', 'SHOPPING', 'BILLS', 'ENTERTAINMENT', 'OTHER', name='expensecategory'), server_default=sa.text("'OTHER'::expensecategory"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('expenses_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('expenses_pkey'))
    )
    op.drop_table('products')
    # ### end Alembic commands ###

    # Clean up the productcategory Enum type
    op.execute("DROP TYPE IF EXISTS productcategory CASCADE")
